services:
  proxy:
    image: caddy:2
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - api
      - ui
      - agent-registry
      - gateway

  gateway:
    build: ../services/gateway
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - PYTHONPATH=/app/src
      - AGENT_REGISTRY_URL=http://agent-registry:8000
      - COORDINATOR_URL=http://coordinator:3000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - agent-registry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  agent-registry:
    build: ../services/agent-registry
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PYTHONPATH=/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build: ../services/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MAC_BRIDGE_URL=http://host.docker.internal:5100
      # Optional: local API key if Bridge enforces it
      # - MAC_BRIDGE_API_KEY=change-me
      - DB_URL=sqlite:////data/agent.db
      - VDB_URL=sqlite:////data/vectors.db
      - PG_URL=postgresql://kenny:kenny@postgres:5432/kenny
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - CALENDAR_REQUIRE_APPROVAL=true
      - CALENDAR_DEFAULT_CALENDAR_ID=
      - AGENT_PERSONA_NAME=Kenny
      # Optional: choose default conversation channel (Phase 2 when sending is enabled)
      # Options: web (default), telegram, whatsapp, imessage
      - AGENT_DEFAULT_CHANNEL=web
      # Optional: approvals via chat by default (UI surfaces approvals in chat)
      # - APPROVALS_CHAT_FIRST=true
      # Optional: embeddings/search tunables
      # - EMBEDDINGS_MODEL=nomic-embed-text
      # - EMBEDDINGS_DIM=768
      # - SEARCH_TOPK_VSS=50
      # - SEARCH_TOPK_FTS=50
      # - SEARCH_TOPK_FINAL=20
      - IMAGE_PROCESSING_ENABLED=false
      - ATTACHMENTS_DIR=/data/attachments
      - AGENT_REGISTRY_URL=http://agent-registry:8000
    volumes:
      - app_data:/data
      - attachments:/data/attachments
    # SQLite runs in-process; no external DB service required
    depends_on:
      - postgres
      - agent-registry



  ui:
    build: ../services/ui
    environment:
      - API_BASE_URL=http://proxy
      - CALENDAR_REQUIRE_APPROVAL=true
      - ENABLE_WEB_CHAT=true
      - AGENT_PERSONA_NAME=Kenny
      # Optional: choose default conversation channel for UI affordances
      # Options: web (default), telegram, whatsapp, imessage
      - AGENT_DEFAULT_CHANNEL=web
      - IMAGE_PROCESSING_ENABLED=false
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=kenny
      - POSTGRES_PASSWORD=kenny
      - POSTGRES_DB=kenny
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Optional: approvals via chat by default in UI
      # - APPROVALS_CHAT_FIRST=true

volumes:
  app_data:
  pg_data:
  attachments:


